{{- if .Values.ingress.privateType.enabled -}}
{{- $fullName := include "python-app.fullname" . -}}
{{- $ingressPath := .Values.ingress.privateType.hostsAndPaths -}}
{{- $servicename := .Values.service.serviceName }}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ $fullName }}-private
  labels:
    app: {{ template "python-app.name" . }}
    chart: {{ template "python-app.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    traffic-type: private
  {{- range $key,$val := .Values.ingress.privateType.labels }}
    {{$key}}: {{$val}}  
  {{- end}}
{{- with .Values.ingress.privateType.annotations }}
  annotations:
{{ toYaml . | indent 4 }}
{{- end }}
spec:
{{- if .Values.ingress.tls }}
  tls:
  {{- range .Values.ingress.tls }}
    - hosts:
      {{- range .hosts }}
        - {{ . }}
      {{- end }}
      secretName: {{ .secretName }}
  {{- end }}
{{- end }}
  rules:
  {{- range $key,$val := .Values.ingress.privateType.hostsAndPaths }}
    - host: {{ $key }}
      http:
        paths:
        {{- range $val }}
          - path: {{ . }}
            backend:
              serviceName: {{ $servicename | default $fullName }}
              servicePort: http
        {{- end}}
  {{- end }}
{{- end }}
